### PR TITLE
Added a config setting to set loop pose for looping animation clips

### PR DESCRIPTION
**Pull request by whalefood**
I realized I didn't want Loop Pose selected for my looping animations, so I made a new setting to be able to change that.  Hoping it made sense to store it in AnimationImporterSharedConfig.  Cheers.

### CODE REVIEW

**Comment by talecrafter** [comment]
Does it make a difference for the animations you're using? The way I understand it Loop Pose is an interpolation between last frame and first frame and as sprites don't get interpolated there should be no difference. Short test I made does seem to reflect that.
So I would suggest just toggling off Loop Pose in all cases to better reflect that there is no interpolation/merging happing here anyway.

**Comment by whalefood** [comment]
Good point.  I updated the code to remove the new setting I added and just always set loop pose off.

**Comment by kira1928** [comment]
Hi, @whalefood 

I found an insignificant problem.
Your indent is different from the existing code.
The original file uses tabs, while the pull request changed it to spaces.

**Comment by talecrafter** [comment]
Fixed this with latest commit. In another file, therefore not using the pull request.
Thanks for pointing this out.

**Pull request closed without merging**
