### PR TITLE
Convert AnimationImporter to Unity package

### PR DESCRIPTION
**Pull request by alexpennells**
Closes issue #33 
Probably worth going over the default values I added for the package

- Removes `*.meta` files from source control
- Moves contents of `Assets/AnimationImporter/` to `Editor/`
- Adds Unity assembly definition 
- Adds package.json

### CODE REVIEW

**Comment by mpewsey** [comment]
This is a fairly old issue / pull request. Are the repository owner's interested at all in implementing this feature? Personally, I would like to see this repository being implemented as a package as opposed to standalone import.

I tried testing @alexpennells branch by importing through `Package Manager > Add package from git URL` but, due to the absence of .meta files in this repository (They are omitted by the .gitignore), the imported package is not functional (No custom menu's, etc.) and produces several warnings. See below:

Screen Shot 2020-08-11 at 7 04 43 PM

The import was performed on Unity 2019.4.6f1.

I think before this branch can be merged, these meta files need to be added. Also, should the method of importing the package be documented in the README? For example, see the [Reorderable List](https://github.com/cfoulston/Unity-Reorderable-List) documentation.

**Comment by GieziJo** [comment]
`*.meta` files indeed need to exist in the folder given that the folder is immutable once imported. I will try to solve the merge conflicts and update the `readme`.

**Comment by GieziJo** [comment]
Implemented in #49 but made in a ways that keeping the same package structure is possible.

**Comment by GieziJo** [comment]
Implemented in #49 but made in a ways that keeping the same package structure is possible.

**Pull request closed without merging**
